Initializing nautilus-dropbox 2019.02.14

(org.gnome.Nautilus:3772): Nautilus-Python-WARNING **: 15:05:05.720: pygobject initialization failed

(org.gnome.Nautilus:3772): Nautilus-Python-WARNING **: 15:05:05.720: nautilus_python_init_python failed
ImportError: could not import gobject (error was: ImportError("cannot import name '_gi' from 'gi' (/usr/lib/python3/dist-packages/gi/__init__.py)"))
Traceback (most recent call last):
  File "/usr/share/nautilus-python/extensions/nautilus-admin.py", line 20, in <module>
    from gi import require_version
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: cannot import name '_gi' from 'gi' (/usr/lib/python3/dist-packages/gi/__init__.py)
Initializing nautilus-dropbox 2019.02.14

(org.gnome.Nautilus:7535): Nautilus-Python-WARNING **: 07:07:40.053: pygobject initialization failed

(org.gnome.Nautilus:7535): Nautilus-Python-WARNING **: 07:07:40.053: nautilus_python_init_python failed
ImportError: could not import gobject (error was: ImportError("cannot import name '_gi' from 'gi' (/usr/lib/python3/dist-packages/gi/__init__.py)"))
Traceback (most recent call last):
  File "/usr/share/nautilus-python/extensions/nautilus-admin.py", line 20, in <module>
    from gi import require_version
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: cannot import name '_gi' from 'gi' (/usr/lib/python3/dist-packages/gi/__init__.py)

(org.gnome.Nautilus:7535): Gtk-WARNING **: 07:12:00.904: Calling org.xfce.Session.Manager.Inhibit failed: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such method “Inhibit”
